# Generated by Django 4.2 on 2023-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_state_remove_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
