# Generated by Django 4.2 on 2023-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profile_pics', verbose_name='Obrazek profilowy'),
        ),
    ]
