# Generated by Django 4.2 on 2023-04-12 17:44

from django.db import migrations
from django.contrib.auth.models import Group


def create_objects(apps, schema_editor):
    # Create INVENTORY group
    inventory_group = Group(name='INVENTORY')
    inventory_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
