# Generated by Django 4.2 on 2023-04-12 17:40

from django.db import migrations
from orders.models import OrderStatus


def create_objects(apps, schema_editor):
    # Create OrderStatus objects here
    status_list = [
        ('Nowy', 'Zamówienie zostało utworzone.'),
        ('W realizacji', 'Zamówienie jest w trakcie realizacji.'),
        ('Wysłano', 'Zamówienie zostało wysłane.'),
        ('Dostarczono', 'Zamówienie zostało dostarczone.'),
        ('Anulowano', 'Zamówienie zostało anulowane.'),
    ]

    for status_name, status_description in status_list:
        status = OrderStatus(name=status_name, description=status_description)
        status.save()


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.RunPython(create_objects),
    ]
